#!/bin/bash

  mkdir ORIGIN
  mkdir WORKING
  mkdir OUTPUT

chmod 755 core/*
cd core
while :
do

  clear

  echo 
  echo "============================================================"
  echo "            HTC HD mini Android Kitchen by Schlund"
  echo "============================================================"
  echo
  echo "  1 - Set up working folder from system.ext2"
  echo
  echo " 99 - Build ROM from working folder"
  echo "  0 - Clean up all folders"
  echo
  echo "  x - Exit"
  echo
  echo 
  echo -n "Enter option: "
  read opt

    case $opt in
      1) clear; ./makefolder;;
      99) ./makesystem;;
      0) ./cleanup;;
      x) clear; echo; echo "Goodbye."; echo; exit 1;;
      *) echo "Invalid option"; continue;;
    esac

done

