#!/bin/bash

  mkdir ORIGIN
  mkdir WORKING
  mkdir OUTPUT

chmod 755 core/*
cd core
while :
do

  clear

  echo 
  echo "============================================================"
  echo "            HTC HD mini Android Kitchen by Schlund"
  echo "============================================================"
  echo
  echo "  1 - Set up working folder from haret files"
  echo "  2 - Collect kernel & modules from compiled kernel source & include"
  echo "  3 - Build haret files from working folder"
  echo
  echo "  0 - Clean up all folders and reset kernel source path"
  echo
  echo "  x - Exit"
  echo
  echo 
  echo -n "Enter option: "
  read opt

    case $opt in
      1) clear; ./makefolder;;
      2) clear;./collectfromsource;;
      3) clear;./makesystem;;
      0) ./cleanup;;
      x) clear; echo; echo "Goodbye."; echo; exit 1;;
      *) echo "Invalid option"; continue;;
    esac

done

