#!/bin/bash

echo
echo "Make a big CleanUp!"
echo

echo "Cleaning ORIGIN..."
rm -rf ../ORIGIN/*
echo "Cleaning WORKING..."
rm -rf ../WORKING/*
echo "Cleaning OUTPUT..."
rm -rf ../OUTPUT/*
echo "Cleaning kernel source path..."
rm -rf ../pathtokernel
echo
echo Finished!
echo
echo "Press Enter to continue"
read enterKey
