#!/bin/bash

echo
echo "Building files from workingfolder"
echo
user_=`whoami`

#CHECK FOR MAIN FOLDERS
if [ -d ../OUTPUT ] && [ -d ../WORKING ]
then
  echo Found main folders...
else
  echo "ERROR At least one main folder not found. Restart the kitchen!"
  read pah
  exit 0
fi

#CHECK FOR FILES IN WORKING FOLDER
if [ -d ../WORKING/system ] && [ `ls -1a ../WORKING/system|wc -l` -gt 2 ]
then
  echo Found system...
  issystemW="y"
fi
if [ -d ../WORKING/initrd ] && [ `ls -1a ../WORKING/initrd|wc -l` -gt 2 ]
then
  echo Found initrd...
  isinitrdW="y"
fi
if [ -f ../WORKING/zImage ]
then
  echo Found zImage...
  iszImageW="y"
fi

if [ "$issystemW" == "" ] && [ "$isinitrdW" == "" ]
then
  echo "ERROR No usesful files found in WORKING folder!"
  read pah
  exit 0
fi

cd ../WORKING

#CHECK FOR FILES IN OUTPUT FOLDER
if [ `ls -1a ../OUTPUT|wc -l` -gt 2 ]
then
  echo
  echo -n "Old files in OUTPUT folder found... remove it (y/n)? (default: y): "
  read do_remove
  if [ "$do_remove" == "n" ]
  then
    exit 0
  fi
  rm -r ../OUTPUT/*
  echo ..removed!
fi

#GETTING STARTED WITH SYSTEM.EXT2
if [ "$issystemW" == "y" ]
then
echo
echo "DOING ON SYSTEM.EXT2:"
echo Preparing..
#sudo chown -R root system/*
num_blocks=`du -sk system | tail -n1 | awk '{print $1;}'`
if [ $num_blocks -lt 20480 ]
then
	extra_blocks=3072
else
        extra_blocks=20480
fi

num_blocks=`expr $num_blocks + $extra_blocks`
num_inodes=`find system | wc -l` ; num_inodes=`expr $num_inodes + 500`

echo num_blocks=$num_blocks num_inodes=$num_inodes extra_blocks=$extra_blocks
echo Building File..
sudo genext2fs -d system -b $num_blocks -N $num_inodes -m 0 ../OUTPUT/system.ext2
#sudo chown -R $user_:$user_ ../OUTPUT/system.ext2
echo Doing some tuning..
sudo tune2fs -L system ../OUTPUT/system.ext2
sudo tune2fs -C 1 ../OUTPUT/system.ext2
echo Checking Filesystem..
sudo e2fsck -fy ../OUTPUT/system.ext2
echo Reverting SYSTEM folder...
#sudo chown -R $user_ system/*
fi

#GETTING STARTED WITH INITRD.GZ
if [ "$isinitrdW" == "y" ]
then
  echo
  echo
  echo "DOING ON INITRD.GZ:"
  cd initrd
  echo "Making file..."
  find | cpio -H newc -o | gzip > ../../OUTPUT/initrd.gz
  cd ..
fi

#GETTING STARTED WITH KERNEL
if [ "$iszImageW" == "y" ]
then
  echo
  echo
  echo "DOING ON KERNEL:"
  echo "Copying Kernel..."
  cp -v zImage ../OUTPUT
fi


echo
echo Finished!
echo
cd ../OUTPUT
ls -lrt
cd ..

echo
echo "Press Enter to continue"
read enterKey

